# POST http://localhost:5004/city-api/register

# Content-Type: application/json

# {
#     "username": "Rohith",
#     "password": "12345",
#     "email" : "rvl@gmail.com",
#     "phoneNumber": 95926018920,
#     "ComplaintID":"10",
#     "complaints": []
# }

# POST http://localhost:5004/city-api/login

# Content-Type: application/json

# {
#     "username": "Rohit",
#     "password": "12345"
# }

POST http://localhost:5004/city-api/login

Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJvaGl0IiwiaWF0IjoxNzY0OTI5NjExLCJleHAiOjE3NjUwMTYwMTF9.0vktc8z7kdTWcu2XHs94D95EFivx4I-LVjGpceboDsc

Content-Type: application/json
{
    "username": "Rohit",
    "password": "12345"
}